baseURL = 'https://mati.byte.uy/'
title = 'BYTE.UY'
paginate = 10

defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false
[languages]
  [languages.es]
    languageName = 'Español'
    weight = 10
    contentDir = 'content/es'
    title = 'BYTE.UY'
    languageCode = 'es-UY'
    [languages.es.params]
      description = 'Blog personal de Matias Arocena'
  [languages.en]
    languageName = 'English'
    weight = 20
    contentDir = 'content/en'
    title = 'BYTE.UY'
    languageCode = 'en-US'
    [languages.en.params]
      description = 'Personal blog of Matias Arocena'


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
