
[[main]]
name = '/home'
pageRef = '/'
weight = 10

[[main]]
name = '/var/logs'
pageRef = '/logs'
weight = 20

[[main]]
name = '/bin/whoami'
pageRef = '/about'
weight = 30

[[main]]
name = '/etc/español'
url = '/'
weight = 40
